### ISSUE TITLE
Can you explain "@app/..." path syntax?

### ISSUE THREAD

**Issue by twigs67** [maciejcieslar/scalable-websocket-nestjs#1]
Hello,

I'm trying to follow along with your article (great btw), but one thing is throwing me off - the "@app/..." syntax you're using to import files. Is this explained in nestjs documentation anywhere?

Thanks

**Comment by maciejcieslar** [comment]
Thanks! The syntax is actually not a part of Nest. It is a feature of TypeScript, read more [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html).

**Comment by twigs67** [comment]
@maciejcieslar Big thanks
